---
- name: ELK
  hosts: all

  tasks:

  - name: Install
    include_role:
      name: install
    when: tasks_type == "install" | default(False)

  - name: Remove
    include_role:
      name: remove
    when: tasks_type == "remove" | default(False)

