- name: Set version
  block:
    - fail:
        msg: "¡Atención! Debes agregar -e 'version=x' donde x es la versión de ELK que intentas instalar. Actualmente puedo ofrecer 6,7 y 8"
      when: version is not defined or version|string != "6" and version|string != "7" and version|string != "8"
    - meta: noop
  when: version is not defined or version|string != "6" and version|string != "7" and version|string != "8"

- name: Importar clave pública de Elasticsearch
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Elasticsearch repository for 8.x packages
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/8.x/apt stable main
    state: present
    filename: elasticsearch-8.x
  when: version == 8

- name: Elasticsearch repository for 7.x packages
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
    state: present
    filename: elasticsearch-7.x
  when: version == 7

- name: Elasticsearch repository for 6.x packages
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/6.x/apt stable main
    state: present
    filename: elasticsearch-6.x
  when: version == 6
