- name: Elasticsearch repository for 8.x packages
  yum_repository:
    name: elasticsearch-8.x
    description: Elasticsearch repository for 8.x packages
    baseurl: https://artifacts.elastic.co/packages/8.x/yum
    gpgcheck: no
    enabled: yes
  when: version == 8

- name: Elasticsearch repository for 7.x packages
  yum_repository:
    name: elasticsearch-7.x
    description: Elasticsearch repository for 7.x packages
    baseurl: https://artifacts.elastic.co/packages/7.x/yum
    gpgcheck: no
    enabled: yes
  when: version == 7

- name: Elasticsearch repository for 6.x packages
  yum_repository:
    name: elasticsearch-6.x
    description: Elasticsearch repository for 6.x packages
    baseurl: https://artifacts.elastic.co/packages/6.x/yum
    gpgcheck: no
    enabled: yes
  when: version == 6
