### IMPORTAR CONFIGURACION ELS

### IMPORTAR CONFIGURACION KIBANA
- name: Configurar Kibana 7
  lineinfile:
    path: /etc/kibana/kibana.yml
    line: 'server.publicBaseUrl: "http://localhost"'
    insertafter: EOF
    state: present
  when: version == "7"

- name: Configurar Kibana 8
  lineinfile:
    path: /etc/kibana/kibana.yml
    line: 'server.publicBaseUrl: "http://localhost"'
    insertafter: EOF
    state: present
  when: version == "8"

### IMPORTAR CONFIGURACION LOGSTASH
