- name: Actualizar lista de paquetes
  yum:
    name: '*'
    state: latest
    update_cache: yes

- name: Instalar dependencias
  yum:
    name:
      - epel-release
      - java-11-openjdk-devel
      - python3-pip
    state: present

- name: pip Install
  pip:
    name:
      - elasticsearch
      - pexpect
    state: present
