- name: Instalando Elasticsearch
  apt:
    name:
      - elasticsearch
  become: yes

- name: Instalando Kibana
  apt:
    name:
      - kibana
  become: yes

- name: Instalando Logstash
  apt:
    name:
      - logstash
  become: yes
