- name: Actualizar lista de paquetes
  yum:
    name: '*'
    state: latest
    update_cache: yes
  become: yes

- name: Instalar dependencias
  yum:
    name:
      - java-11-openjdk-devel
      - python3-pip
    state: present
  become: yes

- name: pip Install
  pip:
    name:
      - pexpect
    state: present
  become: yes
